version: '3.7'

services:
  node-api:
    container_name: node-api
    image: docker/node-api
    build:
      context: .
      dockerfile: docker/js/Dockerfile
    ports:
     - 8123:8123
    environment: 
      DATABASE_HOST: mysql-db-node 
      URL_API_PRODUCT: http://165.227.106.3:8100
      URL_API_CLIENT: http://api-client:8080
      REDIS_URL: redis-auth:6379
      JWT_SECRET: LIHJoihOIJYUTGF45dasf4dsf7a65sadc564dg7
    depends_on:
     - mysql-db-node
    volumes:
     - ./app/src/api:/app
    entrypoint: ["start.sh"]
    links:
      - redis-auth
    networks:
      - app-gateway

  mysql-db-node:
    container_name: mysql-db-node
    image: mysql:5.7
    restart: always
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bhut
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-gateway

  redis-auth:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "63791:6379"
    networks:
      - app-gateway

volumes:
  dbdata:
  redis_data:


networks:
  app-gateway:
    external: true